### ISSUE TITLE
Error: Invalid operands 'int' and 'Callable' in operator

### ISSUE THREAD

**Issue by RedHoodJT1988** [PacktPublishing/Game-Development-Patterns-with-Godot-4#1]
was having an error that was pointing to the original Crate.gd script file saying there was some mismatched types being implemented. When I would hit the LootCrate, it would cause the error and the game would crash. The error Invalid operands 'int' and 'Callable' in operator

**Comment by henriiquecampos** [comment]
Hey @RedHoodJT1988 I couldn't reproduce this issue on my end. Can you provide me the code line and the project it happens(start or finished version)? If you can take a screenshot, it would also help!

**Comment by RedHoodJT1988** [comment]
Hello @henriiquecampos I am not able to reproduce the error again. I might have had a typo somewhere which was causing the issue. Sorry for any inconveniences. I know that when I was originally met with the error, I couldn't figure out what I had done wrong, after a few minutes of looking through my code I decided to use the given solution from the source code and that resolved the issue.

**Comment by RedHoodJT1988** [comment]
Do you want me to close this issue?

**Comment by henriiquecampos** [comment]
Hey there @RedHoodJT1988 , thanks for checking it up again and for reporting the issue! I will close it. Don't hesitate to report further issues
